---
language: objective-c
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.0
# Travis CI Script by Montana Mendy
# Fastlane scan - runs the application tests
script:
- fastlane scan
- echo "What Lane, STILL? How many LANES? Infinite lanes." 
