---
language: objective-c
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.0
# Travis CI .travis.yml by Montana Mendy
# Fastlane scan - runs the application tests
script:
- fastlane scan
- echo "What lane, STILL? How many LANES? Is it infinite lanes? Jake Augunas just made a callback lane, so did Jeff Ward. Can we then lane hop?" 
